### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by maxcaotester**
# Welcome to Cryostat! 👋
## Before contributing, make sure you have:
* [ ] Read the [contributing guidelines](https://github.com/cryostatio/cryostat3/blob/main/CONTRIBUTING.md)
* [ ] Linked a relevant issue which this PR resolves
* [ ] Linked any other relevant issues, PR's, or documentation, if any
* [ ] Resolved all conflicts, if any
* [ ] Rebased your branch PR on top of the latest upstream `main` branch
* [ ] Attached at least one of the following labels to the PR: `[chore, ci, docs, feat, fix, test]`
* [ ] [Signed all commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and last commit is ["signed-off"](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff): `git commit -S -s -m "YOUR_COMMIT_MESSAGE"`
_______________________________________________

Fixes: #<issue number>

## Description of the change:
*This change adds allows the users to provide...*

## Motivation for the change:
*This change is helpful because users may want to...*

## How to manually test:
1. *Insert steps here...*
2. *...*

### CODE REVIEW

**Review by maxcao13 — DISMISSED** [review]
Re do please.

**Review by maxcao13 — COMMENTED** [review]
something something

**Review by maxcao13 — COMMENTED** [review]
comments but not requesting changes

**Review by maxcao13 — DISMISSED** [review]
now i request changes

**Comment by maxcaotester** [comment]
@maxcao13 review please

**Pull request merged**
